# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

# Ref: https://travis-ci.community/t/pip-install-cryptography-fails-on-py36/11233/4
install: pip install -U tox-travis virtualenv

# Command to run tests, e.g. python setup.py test
script: tox

# Create a new token PyPI token for your project via:
# https://pypi.org/manage/account/token/
# Then add it to the `PYPI_PASSWORD` environment variable in your Travis project settings:
# https://travis-ci.com/github/rnag/dataclass-wizard/settings
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  on:
    tags: true
    repo: rnag/dataclass-wizard
    python: 3.8
